### ISSUE TITLE
RESERVED .lu

### ISSUE THREAD

**Issue by GrendelsLair** [weppos/whois#493]
```
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/whois-3.6.2/lib/whois.rb:138:in `bug!': U
nknown status `RESERVED'. Please report the issue at http://github.com/weppos/wh
ois/issues (Whois::ParserError)
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/whois-3.6.2/lib/whois/record
/parser/whois.dns.lu.rb:34:in `block in <class:WhoisDnsLu>'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/whois-3.6.2/lib/whois/record
/parser/base.rb:384:in `block in handle_property'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/whois-3.6.2/lib/whois/record
/parser/base.rb:361:in `cached_properties_fetch'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/whois-3.6.2/lib/whois/record
/parser/base.rb:382:in `handle_property'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/whois-3.6.2/lib/whois/record
/parser/base.rb:230:in `status'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/whois-3.6.2/lib/whois/record
/parser.rb:313:in `delegate_property_to_parsers'
        from C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/whois-3.6.2/lib/whois/record
/parser.rb:279:in `status'
```

**Comment by weppos** [comment]
What is the domain name?

**Comment by GrendelsLair** [comment]
the domain name is: bank-leumi.lu

**Comment by weppos** [comment]
Parsers moved to https://github.com/weppos/whois-parser/
