### ISSUE TITLE
Parser error with .nf domains

### ISSUE THREAD

**Issue by froschi** [weppos/whois#517]
Hi all,

I get parser errors (and the lib crashes) with .nf domains. I installed whois using ``gem install whois``. Here is the code:

```
require 'whois'

> puts Whois::VERSION
3.6.5

> whois = Whois::Client.new
> w = whois.lookup('yahoo.nf')
> w.created_on
=> 2007-09-19 00:51:20 UTC
w.available?
Whois::ParserError: Unknown status `clienttransferprohibited, clientdeleteprohibited, clientupdateprohibited'. Please report the issue at http://github.com/weppos/whois/issues
from /home/thorsten/.rvm/gems/ruby-2.2.3/gems/whois-3.6.5/lib/whois.rb:138:in `bug!'
w.registered?
Whois::ParserError: Unknown status `clienttransferprohibited, clientdeleteprohibited, clientupdateprohibited'. Please report the issue at http://github.com/weppos/whois/issues
from /home/thorsten/.rvm/gems/ruby-2.2.3/gems/whois-3.6.5/lib/whois.rb:138:in `bug!'
```

Similar for microsoft.nf, and others.

Here is the whois command line output for the same tld:

```
$ whois --version
Version 5.1.1.

Report bugs to <md+whois@linux.it>.
$ whois yahoo.nf
Domain Name: yahoo.nf
Domain ID: 100788-CoCCA
WHOIS Server: whois.nic.nf
Referral URL: 
Updated Date: 2015-08-18T09:06:25.37Z
Creation Date: 2007-09-19T00:51:20.829Z
Registry Expiry Date: 2016-09-19T00:51:20.704Z
Sponsoring Registrar: MarkMonitor
Sponsoring Registrar IANA ID: 
Domain Status: clientTransferProhibited
Domain Status: clientDeleteProhibited
Domain Status: clientUpdateProhibited
Registrant ID: 955946-CoCCA
Registrant Name: Domain Administrator
Registrant Organization: Yahoo! Inc.
Registrant Street: 701 First Avenue
Registrant City: Sunnyvale
Registrant State/Province: CA
Registrant Postal Code: 94089
Registrant Country: US
Registrant Phone: +1.4083493300
Registrant Phone Ext: 
Registrant Fax: +1.4083493301
Registrant Fax Ext: 
Registrant Email: domainadmin@yahoo-inc.com
Admin ID: 955946-CoCCA
Admin Name: Domain Administrator
Admin Organization: Yahoo! Inc.
Admin Street: 701 First Avenue
Admin City: Sunnyvale
Admin State/Province: CA
Admin Postal Code: 94089
Admin Country: US
Admin Phone: +1.4083493300
Admin Phone Ext: 
Admin Fax: +1.4083493301
Admin Fax Ext: 
Admin Email: domainadmin@yahoo-inc.com
Tech ID: 955946-CoCCA
Tech Name: Domain Administrator
Tech Organization: Yahoo! Inc.
Tech Street: 701 First Avenue
Tech City: Sunnyvale
Tech State/Province: CA
Tech Postal Code: 94089
Tech Country: US
Tech Phone: +1.4083493300
Tech Phone Ext: 
Tech Fax: +1.4083493301
Tech Fax Ext: 
Tech Email: domainadmin@yahoo-inc.com
Name Server: ns1.yahoo.com
Name Server: ns2.yahoo.com
Name Server: ns3.yahoo.com
DNSSEC: unsigned
Additional Section
Sponsoring Registrar URL: http://www.markmonitor.com
>>> Last update of WHOIS database: 2016-06-29T13:37:48.623Z <<<

[snip]

CoCCA Helpdesk |  support@coccaregistry.org
```

As a side note, I am sure this is fairly easy to fix/integrate into the parser, but I am unsure how. A short manual would help. CONTRIBUTING.md refers to commits which edit files or templates in fixtures/responses, which do not seem to exist in the repo. I don't know how to help.

**Comment by froschi** [comment]
Reformatted original submission for correct display of code blocks.

**Comment by weppos** [comment]
Can you please report it to https://github.com/weppos/whois-parser ?
