### ISSUE TITLE
Parsing response for .me domains fails

### ISSUE THREAD

**Issue by OlliV** [weppos/whois#533]
```
irb(main):001:0> require 'whois'
=> true
irb(main):002:0> Whois.whois('register.me').nameservers
Whois::ParserError: Unexpected token: Access to WHOIS information is provided to assist persons in determining the contents of a domain name registration record in the registry database. The data in this record is provided by
The Registry Operator for informational purposes only, and accuracy is not guaranteed.  This service is intended
only for query-based access. You agree that you will use this data only for lawful purposes and that, under no circumstances will you use this data to(a) allow, enable, or otherwise support the transmission by e-mail, telephone, or facsimile of mass unsolicited, commercial advertising or solicitations to entities other than the data recipient's own existing customers; or (b) enable high volume, automated, electronic processes that send queries or data to the systems of Registry Operator, a Registrar, or Afilias except as reasonably necessary to register domain names or modify existing registrations. All rights reserved. Registry Operator reserves the right to modify these terms at any time. By submitting this query, you agree to abide by this policy.

        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/scanners/base.rb:119:in `error!'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/scanners/base.rb:115:in `unexpected_token'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/scanners/base.rb:111:in `tokenize'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/scanners/base.rb:39:in `parse'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/scanners/scannable.rb:64:in `parse'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/scanners/scannable.rb:70:in `ast'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/scanners/scannable.rb:53:in `node'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/parser/whois.nic.me.rb:45:in `block in <class:WhoisNicMe>'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/parser/base.rb:384:in `block in handle_property'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/parser/base.rb:361:in `cached_properties_fetch'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/parser/base.rb:382:in `handle_property'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/parser/base.rb:230:in `nameservers'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/parser.rb:313:in `delegate_property_to_parsers'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/parser.rb:279:in `nameservers'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record/parser.rb:300:in `method_missing'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record.rb:305:in `nameservers'
        from /home/hbp/.gem/ruby/gems/whois-3.6.5/lib/whois/record.rb:340:in `method_missing'
        from (irb):2
        from /usr/bin/irb:11:in `<main>'

```

**Comment by arthurnum** [comment]
same error for `*.me` names

**Comment by weppos** [comment]
Duplicates https://github.com/weppos/whois-parser/pull/33
